import "@/styles/inter.css";
import "@/styles/vazirmatn.css";
import "@/styles/globals.css";
import Navbar from "@/components/layouts/header/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>

        {children}
      </body>
    </html>
  );
}
